### ISSUE TITLE
Number starts with a dot

### ISSUE THREAD

**Issue by antosha417** [tree-sitter/tree-sitter-json#18]
Hi! 
In [Json spec](https://www.json.org/json-en.html) a number can not start with a dot.
However [according to the grammar](https://github.com/tree-sitter/tree-sitter-json/blob/master/grammar.js#L78) it is possible.

Is this intentional? Would you accept pull request that removes this possibility?

**Comment by CharString** [comment]
The grammar for `number` diverges from the spec in more places. The spec doesn't support "+" as a sign, nor octal or hex literals...

**Comment by amaanq** [comment]
Fixed on master
