### ISSUE TITLE
Program crashing on jsonl files

### ISSUE THREAD

**Issue by P3GLEG** [tree-sitter/tree-sitter-json#30]
Hey there,

I was toying around with tree-sitter and scanning some directories on my system when my program in Rust was randomly dying, and I traced it down to tree-sitter. It turned out I had some ~200mb jsonl files that were being parsed and would crash my program. It looks like something happens after you hit the max of a 16-bit (65536) int somewhere. My debugging is super rusty, and was hoping someone else could take a look. I was able to create a repro in Python as well. You feed it `{}` * unsigned short  int + 1, and it'll crash every time. 

Package version: tree-sitter 0.20.1
Host: MacOS montery 12.6.1 and Ubuntu 20.04.3 LTS
Python version: 3.8.10

## Setup
```bash
mkdir vendor
cd vendor
git clone https://github.com/tree-sitter/tree-sitter-json 
cd ..
python3 repro.py
```

## Repro
```python3
from tree_sitter import Language, Parser

Language.build_library(
  'build/my-languages.so',
  [
    'vendor/tree-sitter-json'
  ]
)

JSON_LANGUAGE = Language('build/my-languages.so', 'json')

parser = Parser()
parser.set_language(JSON_LANGUAGE)


print("Parsing 65536")
to_parse = "{}\n"* 65536
tree = parser.parse(bytes(to_parse, "utf8"))
print("Parsing 65536 finished")

print("Parsing 65537")
to_parse = "{}\n"* 65537
tree = parser.parse(bytes(to_parse, "utf8"))
print("Parsing 65537 finished")
```

## Error generated
```bash
at 01/20/23-11:13:10 in ~/workspace/repro took 46s
[I]   python3 main.py
Parsing 65536
Parsing 65536 finished
Parsing 65537
Parsing 65537 finished
free(): invalid size
[1]    1436038 abort (core dumped)  python3 main.py
```

**Comment by amaanq** [comment]
Can't reproduce atm on master, seems to be fixed
