### ISSUE TITLE
It takes a long time to parse invalid json

### ISSUE THREAD

**Issue by baoti** [tree-sitter/tree-sitter-json#31]
It only takes 0.1s to parse 500KB valid json content, but takes 50s to parse invalid json.
[patch.json.zip](https://github.com/tree-sitter/tree-sitter-json/files/10991776/patch.json.zip)

Invalid json format like:
```json
{
  estimatedNewSize: 49,
  estimatedChangedSize: 3966667,
  estimatedResourceConstrainedSize: 0
}
```

**Comment by amaanq** [comment]
that's a side effect of error recovery.
