### ISSUE TITLE
Add support for JSONL

### ISSUE THREAD

**Issue by Wilfred** [tree-sitter/tree-sitter-json#37]
It would be really nice to support JSONL too. Today tree-sitter-json emits a parse error if there are multiple lines of JSON.

**Comment by amaanq** [comment]
I feel conflicted, if I understand correctly jsonl is just a repeat1 of the json grammar, I'm not sure if we should just support that here or have it be a separate grammar that extends upon the JSON one, my gut says the latter but that also feels excessive for one rule change 😬

**Comment by amaanq** [comment]
Actually, Max already added support for multiple top level values, isn't that what JSONL is effectively?

**Comment by Wilfred** [comment]
Aha, I just need to update past commit 40a81c01a40ac48744e0c8ccabbaba1920441199! Thanks :)
