### ISSUE TITLE
X3D JSON tree-sitter grammar

### ISSUE THREAD

**Issue by coderextreme** [tree-sitter/tree-sitter-json#48]
I am thinking of writing an X3D JSON tree-sitter grammar as a adjunct to X3D JSON schema, here: https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/schema/x3d-4.0-JSONSchema.json My choices for grammar generation are using X3D JSON Schema, X3DUOM, X3D DTD or X3D XML schema:  https://sourceforge.net/p/x3d/code/HEAD/tree/www.web3d.org/specifications/X3dUnifiedObjectModel-4.0.json https://sourceforge.net/p/x3d/code/HEAD/tree/www.web3d.org/specifications/X3dUnifiedObjectModel-4.0.xml https://sourceforge.net/p/x3d/code/HEAD/tree/www.web3d.org/specifications/x3d-4.0.dtd https://sourceforge.net/p/x3d/code/HEAD/tree/www.web3d.org/specifications/x3d-4.0.xsd I have code for processing X3DUOM into X3D JSON Schema: https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/python/etgenerateJSONschema2020-12.py     I don’t know which solution would be best.  I’m hoping for advice.  There are X3D JSON samples here:  https://github.com/coderextreme/X3DJSONLD/tree/master/src/main/data

**Comment by coderextreme** [comment]
Is anyone interested in solving the “generic” problem of JSON schema to tree-sitter grammar conversion.  LLMs can’t handle the scale of my schema.

**Comment by coderextreme** [comment]
Is there a tree-sitter grammar for tree-sitter grammars?

**Comment by maxbrunsfeld** [comment]
> Is there a tree-sitter grammar for tree-sitter grammars?

Tree-sitter grammars are written in JavaScript, so you'd use the JavaScript grammar to parse them.

> Is anyone interested in solving the “generic” problem of JSON schema to tree-sitter grammar conversion. LLMs can’t handle the scale of my schema.

JSON files should just be parsed with the normal Tree-sitter JSON grammar. The schema validation is a separate step, you wouldn't want to handle it with a separate parser.
